import React from 'react';
import { BarChart3, ArrowUpRight } from 'lucide-react';
import { ChartData } from '../../types';

interface ChartVisualizationProps {
  data: ChartData;
}

const ChartVisualization: React.FC<ChartVisualizationProps> = ({ data }) => {
    // Simple SVG calculation helpers
    const width = 600;
    const height = 300;
    const padding = 40;
    const graphWidth = width - padding * 2;
    const graphHeight = height - padding * 2;
    
    const maxValue = Math.max(...data.data.map(d => Math.max(d.value, d.value2 || 0))) * 1.1;
    
    return (
        <div className="mb-6 rounded-2xl overflow-hidden border border-white/10 bg-[#1E1F20]/40 backdrop-blur-md shadow-2xl ring-1 ring-white/5 w-full max-w-[600px]">
            <div className="p-4 border-b border-white/5 flex items-center justify-between bg-white/[0.02]">
                <div className="flex items-center gap-3">
                     <div className="w-8 h-8 rounded-lg bg-gradient-to-br from-[#FF00FF]/20 to-[#9B72CB]/20 flex items-center justify-center border border-white/10">
                        <BarChart3 className="w-4 h-4 text-[#FF00FF]" />
                    </div>
                    <div>
                        <div className="text-sm font-semibold text-[#E3E3E3]">{data.title}</div>
                        <div className="text-[10px] text-[#8E9196] flex items-center gap-2">
                            <span>{data.type.toUpperCase()} CHART</span>
                            <span className="w-1 h-1 rounded-full bg-[#8E9196]"></span>
                            <span>Generated by Gemini</span>
                        </div>
                    </div>
                </div>
                <div className="flex gap-2 text-[10px] text-[#8E9196]">
                     {data.seriesKeys.map((key, i) => (
                         <div key={i} className="flex items-center gap-1.5 px-2 py-1 rounded-md bg-white/5">
                             <div className={`w-2 h-2 rounded-full ${i === 0 ? 'bg-[#4285F4]' : 'bg-[#D96570]'}`}></div>
                             <span>{key}</span>
                         </div>
                     ))}
                </div>
            </div>

            <div className="p-4 relative">
                 <svg viewBox={`0 0 ${width} ${height}`} className="w-full h-auto">
                    <defs>
                        <linearGradient id="grad1" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="0%" stopColor="#4285F4" stopOpacity="0.5"/>
                            <stop offset="100%" stopColor="#4285F4" stopOpacity="0"/>
                        </linearGradient>
                        <linearGradient id="grad2" x1="0" y1="0" x2="0" y2="1">
                            <stop offset="0%" stopColor="#D96570" stopOpacity="0.5"/>
                            <stop offset="100%" stopColor="#D96570" stopOpacity="0"/>
                        </linearGradient>
                    </defs>

                    {/* Grid Lines */}
                    {[0, 0.25, 0.5, 0.75, 1].map((tick, i) => {
                        const y = padding + graphHeight * (1 - tick);
                        return (
                            <g key={i}>
                                <line x1={padding} y1={y} x2={width - padding} y2={y} stroke="rgba(255,255,255,0.05)" strokeWidth="1" />
                                <text x={padding - 10} y={y + 3} textAnchor="end" fill="#8E9196" fontSize="10">{Math.round(maxValue * tick)}</text>
                            </g>
                        );
                    })}

                    {/* Area Chart Logic */}
                    {data.type === 'area' && (
                        <>
                             {/* Series 1 */}
                             <path 
                                d={`M ${padding} ${height - padding} ` + data.data.map((d, i) => {
                                    const x = padding + (i / (data.data.length - 1)) * graphWidth;
                                    const y = padding + graphHeight * (1 - d.value / maxValue);
                                    return `L ${x} ${y}`;
                                }).join(' ') + ` L ${width - padding} ${height - padding} Z`}
                                fill="url(#grad1)"
                             />
                             <polyline 
                                points={data.data.map((d, i) => {
                                    const x = padding + (i / (data.data.length - 1)) * graphWidth;
                                    const y = padding + graphHeight * (1 - d.value / maxValue);
                                    return `${x},${y}`;
                                }).join(' ')}
                                fill="none"
                                stroke="#4285F4"
                                strokeWidth="2"
                             />

                             {/* Series 2 (Optional) */}
                             {data.seriesKeys.length > 1 && (
                                <>
                                 <path 
                                    d={`M ${padding} ${height - padding} ` + data.data.map((d, i) => {
                                        const x = padding + (i / (data.data.length - 1)) * graphWidth;
                                        const y = padding + graphHeight * (1 - (d.value2 || 0) / maxValue);
                                        return `L ${x} ${y}`;
                                    }).join(' ') + ` L ${width - padding} ${height - padding} Z`}
                                    fill="url(#grad2)"
                                    opacity="0.7"
                                 />
                                 <polyline 
                                    points={data.data.map((d, i) => {
                                        const x = padding + (i / (data.data.length - 1)) * graphWidth;
                                        const y = padding + graphHeight * (1 - (d.value2 || 0) / maxValue);
                                        return `${x},${y}`;
                                    }).join(' ')}
                                    fill="none"
                                    stroke="#D96570"
                                    strokeWidth="2"
                                 />
                                </>
                             )}
                        </>
                    )}

                    {/* Bar Chart Logic */}
                    {data.type === 'bar' && data.data.map((d, i) => {
                        const x = padding + (i / data.data.length) * graphWidth + (graphWidth / data.data.length) * 0.1;
                        const barWidth = (graphWidth / data.data.length) * 0.3;
                        const y = padding + graphHeight * (1 - d.value / maxValue);
                        const heightBar = height - padding - y;
                        
                        // Second Series vars
                        const y2 = d.value2 ? padding + graphHeight * (1 - d.value2 / maxValue) : 0;
                        const heightBar2 = d.value2 ? height - padding - y2 : 0;

                        return (
                            <g key={i}>
                                <rect x={x} y={y} width={barWidth} height={heightBar} fill="#4285F4" opacity="0.9" rx="2" />
                                {d.value2 && (
                                    <rect x={x + barWidth + 4} y={y2} width={barWidth} height={heightBar2} fill="#D96570" opacity="0.9" rx="2" />
                                )}
                            </g>
                        );
                    })}

                    {/* X Labels */}
                    {data.data.map((d, i) => {
                        const x = padding + (i / (data.type === 'area' ? data.data.length - 1 : data.data.length)) * graphWidth + (data.type === 'bar' ? (graphWidth/data.data.length)*0.25 : 0);
                        return (
                             <text key={i} x={x} y={height - padding + 20} textAnchor="middle" fill="#8E9196" fontSize="10">{d.label}</text>
                        );
                    })}
                 </svg>
            </div>
            
            {data.summary && (
                <div className="px-4 py-3 bg-[#131314]/30 text-xs text-[#E3E3E3] border-t border-white/5 flex items-start gap-2">
                    <ArrowUpRight className="w-4 h-4 text-[#34A853] flex-shrink-0" />
                    <span className="leading-relaxed">{data.summary}</span>
                </div>
            )}
        </div>
    );
};

export default ChartVisualization;